name: artbox
channels:
  - nodefaults
  - conda-forge
dependencies:
  - pygobject
  - python >=3.8.1,<4
  - cairo 1.18
  - pycairo 1.25.1
  - pip
  - poetry
  - nodejs # used by semantic-release
  - shellcheck
  - pip:
      - paginate
