name: build

on: [push, pull_request]

jobs:
  check-pr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: check-pr-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if the PR's branch is updated
        uses: osl-incubator/gh-check-pr-is-updated@1.0.0
        with:
          remote_branch: origin/main
          pr_sha: ${{ github.event.pull_request.head.sha }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "1.*"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: artbox
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: makim tests.unittest

      - name: Run style checks
        run: makim tests.linter
